### ISSUE TITLE
Supresses forward slash for quick find in all tabs

### ISSUE THREAD

**Issue by jeremybourque** [ancestorak/brief#102]
The forward slash shortcut that is supposed to open quick find no longer works on any tabs. Disabling Brief causes the shortcut to work again. Interestingly, if the apostrophe shortcut is used to open quick find (links only) then the forward slash shortcut works again but only on the tab where quick find (links only) was opened.

**Comment by MichaelEischer** [comment]
This bug has sort of inverted itself by now. At least with Firefox Nightly 51 the forward slash shortcut is no longer working.

**Comment by tanriol** [comment]
Seems to be fixed in 2.3b1(in both variants of the bug).
