### ISSUE TITLE
Remove the "home folder" concept entirely

### ISSUE THREAD

**Issue by tanriol** [ancestorak/brief#114]
Inspired by #93, what if we force home folder == All Bookmarks?

This allows us to avoid the whole idea of a special magic "Subscribed Feeds" folder at the price of a few extra nesting levels for most feeds. However, they can be neutralized by collapsing the common parents of all feeds in a header with no indentation for this nesting level.

This leaves the problem that a user may want only a subset of their livemarks to be accessed by Brief. I don't have a solution yet... maybe make it possible to mark folders as ignored.

**Comment by ancestorak** [comment]
I think marking folders as ignored would present a problem interface-wise. The simplest way would be to do it from the context menu or the properties window, but how would the user unignore them once they are hidden from Brief? Through the Library window? That's not very discoverable, not to mention that it would require a lot of effort to integrate. A list of ignored folder in the Brief's options window? More reasonable but seems rather ugly to me.

Another problem is it would make subscribing more complicated. We've just made it one-click but now the user would again have to choose the folder where to put the feed. This is a definite usability regression. I suspect most users don't even arrange their feeds into sub-folders and for them this step is completely unnecessary. Even if you *do* arrange your feeds, it is still more streamlined to just add the feed right away and let you organize stuff later if you want.

All in all, I'm leaning towards WONTFIX.

**Comment by tanriol** [comment]
> The simplest way would be to do it from the context menu or the properties window, but how would the user unignore them once they are hidden from Brief?

What about showing them in the sidebar greyed-out or (if multiple) as collapsed "N ignored"?

> Another problem is it would make subscribing more complicated. We've just made it one-click but now the user would again have to choose the folder where to put the feed.

It may be added to the root or a default folder.

> I suspect most users don't even arrange their feeds into sub-folders and for them this step is completely unnecessary. Even if you do arrange your feeds, it is still more streamlined to just add the feed right away and let you organize stuff later if you want.

An interesting point. However, as for me, it's the other way round - I have about 150 feeds in multiple nested folders and really prefer to put a new feed into the correct one right away because I often view feeds by folders and expect the newly added feed to show up in the correct folder.

The automagic Brief folder is pretty usable with a single Firefox (after all, one can rename and move it into place). However, if multiple computers use Firefox Sync, users may expect to have only one feed list or to have two (or, possibly, for one to be a subfolder of the other). I have no idea of a nice way to support all these use cases.

**Comment by tanriol** [comment]
Or may we just bring back the ability to change the home folder by putting it into the folder's context menu in Library?

**Comment by ancestorak** [comment]
> What about showing them in the sidebar greyed-out or (if multiple) as collapsed "N ignored"?

That's a better idea, I think.

> It may be added to the root or a default folder.

The root is rarely what the user wants, so that's out. A default folder... but then you would have to have an option to choose the default folder, at which point we may as well bring back the option to change the home folder, as you say yourself.

Anyway, I don't see any insurmountable problems with the current setup in the context of sync integration. Could you please describe in #93 the exact problem scenarios?

**Comment by ancestorak** [comment]
WONTFIX-ing per [this comment](https://github.com/ancestorak/brief/issues/93#issuecomment-84474759).
