### ISSUE TITLE
"view headlines" option is not saved

### ISSUE THREAD

**Issue by micnic** [ancestorak/brief#117]
After I close the Brief's tab the "View headlines" options is not saved, I always get the feeds expanded (not collapsed as expected).

Brief 2.0b1

**Comment by tanriol** [comment]
Please try [Brief 2.0b2](https://github.com/ancestorak/brief/releases/tag/v2.0b2), this sounds like a known bug that should be fixed there.

**Comment by micnic** [comment]
thanks, its fixed in the 2.0b2, but I found another bug :D, should I add another issue?

**Comment by tanriol** [comment]
Sure, you're welcome. One issue per bug is preferred.
