### ISSUE TITLE
broken feed example: empty second entry, cannot mark items as read

### ISSUE THREAD

**Issue by azrdev** [ancestorak/brief#120]
I subscribed the following feed, and it is broken in Brief `2.0b3`: https://connected.tante.cc/feed/
That is:

1. The feed tree listing of Brief shows not only the normal entry of the subscription, but also directly below that a second one *without title*, which shows exactly the same items if I select it. The unread counter is not displayed for that additional item.
2. I cannot mark items in the feed as read. The caption of the according button says "Mark item as read", if I click on it (or press M) it doesn't change, and the unread-counter remains 10. This is true for both "feeds" from 1.
3. The unread-counter (10) is not part of the global unread counter.
4. The dynamic bookmark displays fine in the normal firefox library views.

**Comment by tanriol** [comment]
@azrdev, I haven't managed to reproduce this bug. The feed you demonstrate works for me. Could you please check whether you can reproduce it in a clean Firefox profile?

**Comment by azrdev** [comment]
@tanriol yeah, seems like I somehow removed the kludge in my profile, the problem is gone now. Thanks for caring nevertheless!
