### ISSUE TITLE
Cannot add new feeds

### ISSUE THREAD

**Issue by lcoulet** [ancestorak/brief#121]
Brief continues to work with existing feeds but doesn't work when I add new feeds in the bookmarks.

A new Firefox profile with new feeds doesn't work either, brief remains empty.

**Comment by tanriol** [comment]
What version are you using?
Please try the current test version [2.0b3](https://github.com/ancestorak/brief/releases/tag/v2.0b3) if using an older one, as this sounds like a known problem that should already be fixed.

**Comment by lcoulet** [comment]
I was using 1.7.3 (the regular version on mozdev.
After upgrading to 2.0b3 it is running just fine !

Thanks a lot, I close this issues.
Loic
