### ISSUE TITLE
Cached RSS feeds prevent refresh in Brief

### ISSUE THREAD

**Issue by torgeirsh** [ancestorak/brief#123]
Brief is unable to update feeds from twitrss.me due to some kind of caching. If I eventually open one of the RSS feed directly in the browser and manually click reload, then Brief will pick up the updates on its next refresh, but having to do that everytime for all feeds is a bit counterproductive. Can Brief bypass the cache when reading feeds?

**Comment by tanriol** [comment]
Not sure whether this behaviour will be correct. Automatically fetching on a schedule with forced cache bypass is... not exactly nice to the servers.

On the other hand, the `twitrss.me`'s reply headers seem really weird.
@ciderpunx, when requesting `http://twitrss.me/twitter_user_to_rss/?user=foxnews`, in the reply headers I see

```
CF-Cache-Status: HIT
CF-RAY: 1aab92f4ff181595-FRA
Cache-Control: public, max-age=2591034
Connection: keep-alive
Content-Type: application/rss+xml
Date: Sun, 18 Jan 2015 14:45:02 GMT
Expires: Tue, 17 Feb 2015 14:28:56 GMT
Server: cloudflare-nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding
Via: 1.1 varnish
X-Varnish: 1201818528
```
Do you really intend the RSS feed to be cached by the feed reader for a month(!)? Should the reader follow the directives or ignore them?

**Comment by torgeirsh** [comment]
It may not be nice, but on the other hand, if the cache isn't bypassed, there's no point in refreshing the feed at all...

**Comment by torgeirsh** [comment]
It seems that Brief does not honour the browser.cache.check_doc_frequency setting. I tried setting it to 1 so that documents are checked for new versions on every load, but Brief doesn't detect any new posts from the twitrss.me feed. If I open the feed in the browser instead, this time I get the updated version without explicit reload, but somehow Brief bypasses the setting.

**Comment by torgeirsh** [comment]
I've tried adding

    this.request.channel.loadFlags |= Components.interfaces.nsIRequest.LOAD_BYPASS_CACHE;

to the requestFeed function, but when I refresh a feed, the spinning icon by the feed that normally disappears quickly just stays there and nothing happens. I have no idea how to debug extensions or find out what's wrong, and stupid tricks like calling alert or throw an Error doesn't seem to do anything (nothing shows up in the built-in javascript console). Could someone please look into this and point me to the right direction so I at least can fix this problem locally if cache bypassing isn't wanted in the main release?
