### ISSUE TITLE
Deleted RSS feeds come back by themselves

### ISSUE THREAD

**Issue by nyorogithub** [ancestorak/brief#124]
After deleting a feed within the Brief addon, it will come back by itself on the refresh of the feeds.
Also, if you delete the feed using Firefox's Bookmarks Manager, it doesn't make a difference. It appears to be permanently stuck/stored.

**Comment by tanriol** [comment]
What Brief version are you using? Does it work correctly with Brief [2.0b3](https://github.com/ancestorak/brief/releases/tag/v2.0b3)? The AMO versions 2.0b1 and 1.7.3 are, unfortunately, out-of-date and may have problems with feed list modification.

**Comment by nyorogithub** [comment]
I am using 1.7.3. Sorry, I should have read the home page of the blog a bit closer. I will install the latest version.

Thanks for the fast response.

**Comment by nyorogithub** [comment]
Upgrading fixed the issue.
