### ISSUE TITLE
No longer updating...

### ISSUE THREAD

**Issue by Anandajoti** [ancestorak/brief#127]
I have 1.7.3 installed. Recently when I add a new feed to Brief it doesn't appear. I also cannot edit any of the feeds, as though it has become read-only. I tried restarting FF, reloading the page, etc. Any ideas what else to try?

**Comment by Anandajoti** [comment]
Here is a screenshot, the red outlined items haven't shown in Brief:

![2015-01-25 12 31 53](https://cloud.githubusercontent.com/assets/6820865/5890266/534d0a00-a48e-11e4-90fd-2de83acbcee6.png)

**Comment by tanriol** [comment]
A known bug, 1.7.3 is broken at the moment. You're recommended to switch to [2.0b3 development version](https://addons.mozilla.org/firefox/downloads/file/294808/brief-2.0b3-fx.xpi?src=dp-btn-devchannel).

**Comment by Anandajoti** [comment]
Thanks for the quick reply. That's partially fixed it, but the top item in the chosen location shows near the bottom. See the image.

![2015-01-25 15 52 59](https://cloud.githubusercontent.com/assets/6820865/5890820/66631b5e-a4aa-11e4-9d1b-8a9bf0960381.png)

**Comment by tanriol** [comment]
Hm. Does it stay there even if you use Organize and move it in the bookmark list?

**Comment by Anandajoti** [comment]
OK, just checked, and it seems now it adds at the bottom at the beginning, but when moved in the bookmarks it does respond and move to the correct position. Many thanks for a great addon.

**Comment by tanriol** [comment]
How can one actually add a bookmark straight into the middle of the folder? I don't know any way.
