### ISSUE TITLE
Doesn't import dynamic bookmark

### ISSUE THREAD

**Issue by Kyphala** [ancestorak/brief#129]
Installing Brief addon V 1.7.3 and also set the dynamic bookmark folder to correct place.
The bookmarks in firefox (35.0.1) workin fine but the brief addon didn't import them.
Also adding new feeds only add them to the dynamic bookmark but not to brief itselfe.

**Comment by tanriol** [comment]
Please install the development version (2.0b3), as 1.7.3 does not work with current Firefox versions.
