### ISSUE TITLE
2.0 beta needs translation/localization

### ISSUE THREAD

**Issue by genodeftest** [ancestorak/brief#130]
Is there a way to translate brief into my native language?

**Comment by tanriol** [comment]
Brief used to be translated with Babelzilla.
Currently, only 1.7 is there, and I have no permission to upload 2.0.
I've asked @ancestorak to do that, but no answer yet.

As for now you may try updating it in `chrome/locale` manually using `en-US` as an example and uncomment in `install.rdf`.

**Comment by tanriol** [comment]
@genodeftest, ready for translation [on Babelzilla](http://www.babelzilla.org/index.php?option=com_wts&Itemid=264&extension=3705&type=lang).

**Comment by genodeftest** [comment]
Bad thing is they don't even have a HTTPS connection available.

**Comment by genodeftest** [comment]
Babelzilla is completely broken. With a fresh Firefox profile I cannot even submit changes to files or access the bug tracker.

**Comment by tanriol** [comment]
I used it for the Russian translation just weeks ago and everything worked OK. Yes, it's not up-to-date with all the trends of the year, but it still works, at least till the two-weeks-ago Nightly version of Firefox.

**Comment by genodeftest** [comment]
It doesn't for me with a default firefox (not nightly) and a default fresh profile. I contacted the admin about that, let's see what happens.
