### ISSUE TITLE
Brief favorites suddenly gone

### ISSUE THREAD

**Issue by paraver** [ancestorak/brief#131]
Hi there.

Firstly I must thanks for this useful addon.

Until yesterday Brief was just fine. Today, after opening FF 28.0 with Brief 1.7.2 (no update is shown) all feeds that I had in favorite just disappeared. All of them! How can I get back that data?

Regards

**Comment by tanriol** [comment]
1.7.2 is outdated. Please install the Brief 2.0b3 development version.

**Comment by paraver** [comment]
Hi tehre.

Despite that, is there any tip to overcome this problem?

Now, after favoriting a feed, after cleaning the feed, everything is deleted. The favorited feed also.

**Comment by tanriol** [comment]
Have you installed development [Brief 2.0b3](https://addons.mozilla.org/firefox/downloads/file/294808/brief-2.0b3-fx.xpi?src=dp-btn-devchannel)? It is the only version that is known to work now. Feel free to reopen this bug if there are any bugs with the new version.

**Comment by paraver** [comment]
When trying to install, the operation is cancelled because it is not compatible with FF 28.

**Comment by tanriol** [comment]
Oops, excuse me, I overlooked this. FF 28 is not supported by the development version... on the other hand, the old version is expected to work OK there. Sorry for the confusion.

Do you mean "all feeds that I had in favorite" to be "all feeds in the list", "starred (bookmarked) entries" or something else?

Brief stores its feed list as Firefox bookmarks. Could you please check whether the live bookmarks are still in the Subscribed feeds folder?

**Comment by paraver** [comment]
I referred to those that were bookmarked.

In a bookmarked item, if I choose "mark entry as read", the item seems to be removed. 

Another issue, is that on Brief's left panel, right click and choosing "empty feed", all bookmarks will be removed, even those that are bookmarked.

Yes, live bookmarks are in the subscribed feeds folder.

Thank you for your attention.

**Comment by AussieD** [comment]
[I hope Denis doesn't mind me jumping in here to help lighten his load]

 

With regard to the issues you have raised:

 

1)       It sounds like you have filtered to only show unread bookmarks. I
forget exactly what it's called in earlier Brief versions, but it should be
called something like "show only unread items" (usually keyboard shortcut
"D").

 

2)       The "empty feed" command does just that - it empties that feed's
entire content! Any (permanent) bookmarks that you have stored will likely
still be stored by FF, but you won't be able to view them in an empty feed
using Brief. Try looking in the FF's Unsorted Bookmarks folder to find them.

 

It might be helpful to point out that within FF's bookmarks regime is
capable of housing two things: 1) static bookmarks (which we all know
about); and 2) dynamic RSS feeds. FF defaults to store RRS feeds in the
Subscribed Feeds folder. Brief is only a reader that reads the Subscribed
Feeds folder/sub-folders. Whenever you bookmark an item using Brief it will
permanently store the bookmark in a static FF bookmark folder. If you don't
specify a location the new bookmark will be stored in the Unsorted Bookmarks
folder. These permanent (static) bookmarks are stored independently to the
static RSS feeds, meaning you can delete an RSS item (or even an entire
feed) and any bookmarks you marked will still remain. Naturally, you will
not be able to view them using Brief if you have already emptied the feed
(remembering that Brief only shows active feed items stored in the
Subscribed Feeds folder). FFs decision to store RSS feeds within its
bookmark ecosystem might seem a little confusing at first, but once you
understand the basics it should become much clearer.

 

 

 

  _____

**Comment by tanriol** [comment]
@AussieD, thank you for help. Really sounds like the unread only filter.

**Comment by paraver** [comment]
Dear Aussie and tanriol,

Many thanks! The "issue" is solved.

I do not know how it became filtered.

Sorry to bother.

Once again, many thanks.
