### ISSUE TITLE
Some images do not render (show as black or distorted/corrupted render

### ISSUE THREAD

**Issue by MDnnrd** [ancestorak/brief#135]
I use Cyberfox x64 AMD and after updating to v. 35.0X, some images do not render, but if you open into another tab, they show.  I haven't figured out if this is within the rendering engine, graphics card, antivirus, etc.  This did not happen until the code was updated to version 35. It is random and not with a particular image format. At first I thought it might be the image preview for a video, but those show as a static image (the context menu is different when right click on those). I am using 2b3 of Brief, Windows 8.1 x64 Pro, and can provide more stats if needed. I also use ublock nightly, but if it was interfering it would be blocking all images. GIF's are also slow to load and cause delayed prefeching as scrolling through a web page. I have tried different settings on different levels of software/hardware and no avail.

**Comment by tanriol** [comment]
Does this happen to the same images over and over? Could you please provide an example of such feed and/or verify whether they do open in Firefox? I haven't seen such bugs yet (Firefox 35.0 or Nightly, Linux amd64).

**Comment by tanriol** [comment]
Closing this issue as never confirmed in almost a year.
