### ISSUE TITLE
Problem with bookmarked (stared items)

### ISSUE THREAD

**Issue by Just4code** [ancestorak/brief#140]
I'd also like to thank you for your efforts of keeping good old app alive.
A few remarks that might help debugging following issue.

Using FF36.0 on three different XP & win7.
Removed old Brief, installed 2.0b3, deleted brief.* and started with a clean DB.
My old feeds were kept without problem and reappeared on the left panel.
Updating feeds, adding, removing presents no problems.
There is a problem with bookmarking (staring) items.
The same behavior was confirmed and replicated on all three systems as follows.
While reviewing the feeds, an item -or more than one - is marked 'stared' (bookmarked).
Then select bookmarks on the panel on the left. Select expanded view (from the buttons on the top of page).
Try to remove the star (unbookmark) from the items controls.
You will notice that it takes two clicks.
The first click removes the bookmark from places.sqlite - but the star remains and also the item remains in the bookmarked list.
The second time the star is finally removed.
Also, after clicking to remove the star, the view is refreshed and most of the times items are lost from the display. Sometimes, not all of the items are lost but you have to select 'all items' on the left and then 'bookmarks' again to view remaining items.
I just hope that does not corrupt the database.
It would also be nice if stars were also visible while in compressed list (just the tiles view) otherwise you have no way to remove the stars while in this compressed view.

I must also admit that the positioning of icons was more practical with old brief, but there is always a field for improvement with every application.
Cheers

**Comment by tanriol** [comment]
Sorry for a long delay.

Confirmed the bug about two clicks required to remove a bookmark (Firefox 41, latest Brief).
