### ISSUE TITLE
Toolbar icon on Mac incorrectly aligned within button

### ISSUE THREAD

**Issue by TGOS** [ancestorak/brief#143]
The icon seems top aligned within the button but I think it should be vertically centered. 
It's a bit hard to explain, so I added an animated GIF:

![iqucc](https://cloud.githubusercontent.com/assets/8492950/6617256/3034ab66-c8b7-11e4-9f6e-cba4dba14a36.gif)

I'm using 2.0b3

**Comment by tanriol** [comment]
The button is also misaligned in the menu in Linux.

**Comment by tanriol** [comment]
Should be fixed with #172.
