### ISSUE TITLE
Brief 1.7.3 Incompatible with Firefox 36.0. Time to push 2.0 to the website? 

### ISSUE THREAD

**Issue by carlosgs** [ancestorak/brief#145]
I didn't know of the 2.0 version in Github until now, when firefox simply disabled Brief.
![screenshot from 2015-03-15 11 28 57](https://cloud.githubusercontent.com/assets/1636266/6655805/80fa7d36-cb06-11e4-9386-9df75624148b.png)
What is the cause of maintaining 1.7.3 as "stable" in the website?
Oh and thank you for this very useful extension! :-)

**Comment by tanriol** [comment]
@ancestorak is going to push it in a few days. The current delay is due to UI translation.

**Comment by carlosgs** [comment]
Awesome, thanks!

**Comment by tanriol** [comment]
2.0 is published, so closing.
