### ISSUE TITLE
Feeds containing <article> elements display incorrectly

### ISSUE THREAD

**Issue by Artfunkel** [ancestorak/brief#147]
For example, http://what-if.xkcd.com/feed.atom.

The issue is that the root of each item in the above feed is an `article` element, and this picks up a CSS rule intended only for Brief's own `article` elements.

The fix I've made locally is to change the selector at feedview.css:23 to read `#feed-content > article`.

**Comment by tanriol** [comment]
This is a variant of #69.

**Comment by tanriol** [comment]
Fixed by f15890c
