### ISSUE TITLE
Keyboard shortcuts don't work in FF 40

### ISSUE THREAD

**Issue by DuncanL** [ancestorak/brief#149]
Keyboard shortcuts don't work in FF 40 - it just does a search within the page (so you can't quickly mark things as read,  just fine the first instance of 'm' on the page!)

**Comment by tanriol** [comment]
Confirmed on Nightly 42 that the Preferences option "Search for text when I start typing" breaks the Brief's shortcuts (at least m, u, i).

**Comment by tanriol** [comment]
Should be working correctly in master.
