### ISSUE TITLE
Opening tutorial from empty feeds view doesn't work in Fx 38+

### ISSUE THREAD

**Issue by nohamelin** [ancestorak/brief#150]
In an empty feed view, the link:

    You haven't added any feeds yet.
    "See how to do it!"

doesn't do anything; in the browser console the next message is triggered:
```
Security Error: Content at resource://brief-content/feedview.html 
may not load or link to chrome://brief/content/firstrun.xhtml?tutorial.
```
Seen in Fx 38.0.5 and 39.0, using Brief 2.0.1-signed

**Comment by nohamelin** [comment]
Nice, but opening the tutorial should not be triggered right-clicking on the link.

**Comment by tanriol** [comment]
Oops, missed this.
