### ISSUE TITLE
Bried 2.0b3 could not be verified for use in Firefox Developer Edition and has been disabled

### ISSUE THREAD

**Issue by r03ert0** [ancestorak/brief#152]
Hello,
since the last update (yesterday?) Brief is disabled by FF (along with several other extensions). The extensions panel only gives me now the possibility of removing Brief, but not to force activation.

thank you,

roberto

**Comment by Keith94** [comment]
Go to about:config and toggle the **xpinstall.signatures.required** preference.

**Comment by tanriol** [comment]
Or use Brief from AMO as it's automatically signed there.

**Comment by sabret00the** [comment]
@tanriol Most people use the development channel via AMO don't they?

**Comment by tanriol** [comment]
@sabret00the, the *latest* Brief from AMO is signed `2.0.1-signed`, AFAIK. Do you mean that the development channel users are never updated to the final release because it's not a development version?

**Comment by nohamelin** [comment]
@tanriol Exactly.

If a new development version is pushed to AMO, it will be signed:
https://blog.mozilla.org/addons/2015/08/12/add-ons-update-69/comment-page-1/#comment-218412

**Comment by sabret00the** [comment]
@tanriol basically what @nohamelin said. If a new development build is pushed to AMO, this becomes a non issue.

**Comment by tanriol** [comment]
This should be done as 2.2b1 is on AMO.
