### ISSUE TITLE
Consider Full YouTube API v3 Support

### ISSUE THREAD

**Issue by Ngamer01** [ancestorak/brief#153]
Earlier in the year, YouTube has updated their APIs from version 2 to version 3 which means their RSS feeds have changed.

Currently Brief does display feeds that use version 3 of the API, but unfortunately, Brief does not show video thumbnails or descriptions like version 2 RSS feeds did.

https://www.youtube.com/feeds/videos.xml?channel_id=UCVyr0QjyHKZQP4ej0YI1Apg

Here is an example of a version 3 RSS feeds.  You can see it doesn't tell you much other than video titles and who posted the videos.  If it's possible (whether if Brief needs to add support or if YouTube can be contacted about this), I would like thumbnail and video description support added to Brief.

**Comment by tanriol** [comment]
Is this a different issue from #5?

**Comment by Ngamer01** [comment]
Originally I wasn't sure, but after looking at this page (http://www.rssboard.org/media-rss) it seems this issue is a duplicate of #5.  Sorry for the duplicate report.

**Comment by tanriol** [comment]
No need to be sorry, you've provided an extra evidence that the functionality is desireable.
