### ISSUE TITLE
Broken after bookmarks restore

### ISSUE THREAD

**Issue by nsubiron** [ancestorak/brief#157]
Suddenly all my live bookmarks became folders and all the feeds where lost (I have no idea why neither if it's brief's fault or not). I restored all bookmarks to the previous version and the live bookmarks are back but brief is no longer showing them. A new 'Subscribed Feeds' folder appeared, so I copied there the old bookmarks but still nothing. Even more I subscribed to new feeds and those appear and update in brief but are missing in the bookmarks, and do not appear even when clicking in 'organize' feeds. So I can add new feeds, but I'm not able to organize them.

Seems to be an odd situation, I have two 'Subscribed Feeds' folders and none of them seems to be the home folder of brief, meanwhile new feeds are stored somewhere but somehow are not visible as Firefox bookmarks.

I tried updating to v2.0b3 (previously I had the last signed version) and removing and reinstalling the plugin but the problem persists. 

I also have Firefox Sync active in two machines, that could be the reason things got messed up in the first place.

**Comment by sleek22** [comment]
nsubiron,

When you restore your bookmarks, the folder number changes. Here is how you fix it.

Install an add-on called SQLite Manager. Open up the places.sqlite database. Click on "moz_bookmarks. Do a search for "Subscribed Feeds". That will give you the folder number you need. Write down this folder number. ( I would suggest that you delete one or the other folder you have in your case leaving one folder before you start).

Now, open up about:config in Firefox and do a search for "homefolder". The result will give you Brief's home folder. Enter the folder number you obtained from the previous step. Brief will then see your feeds.

**Comment by nsubiron** [comment]
Thanks @sleek22, yes that fixed it. I also found out where the new feeds were going, it turns out the old home folder id was reused after restore for an existing folder deep in some directory tree in my bookmarks. Brief was adding the feeds there instead of creating a new folder.

**Comment by tanriol** [comment]
> it turns out the old home folder id was reused after restore for an existing folder deep in some directory tree in my bookmarks.

Hmm, never seen such an effect, but certainly possible. Opened #158 for this bug.
