### ISSUE TITLE
Root folder may change unexpectedly in the case of bookmark restore changing folder IDs

### ISSUE THREAD

**Issue by tanriol** [ancestorak/brief#158]
See #157. This will be partially mitigated if we allow changing the root folder (#156), but a proper fix is also needed.

**Comment by ajgelado** [comment]
Got bitten by this bug, too. Solved it looking for the new bookmarks folder's ID using SQLite Manager and then entering it manually in the extensions.brief.homeFolder key at about:config.

**Comment by tanriol** [comment]
No longer happens due to losing the possibility of livemarks sync.
