### ISSUE TITLE
Unsubscribe functional broken

### ISSUE THREAD

**Issue by micnic** [ancestorak/brief#162]
If I unsubscribe from a feed it is removed from the list, but on tab refresh it appears again, also if there are some unread items in the unsubscribed feed they remains in the unread list, I guess they are related. Version 2.0.1 - signed.

**Comment by tanriol** [comment]
Confirmed on Firefox 41 with latest Brief, unsubscribe throws `Trying to update the GUIDs cache with an invalid itemId` from `PlacesUtils.jsm`.
