### ISSUE TITLE
TypeError: getTopWindow(...).gBrowser is undefined

### ISSUE THREAD

**Issue by vovkkk** [ancestorak/brief#164]
Could it be possible to make Brief work in pop-up window?

I create popup with 

``` js
            windows.openDialog({url: open_this, name: '',
                features: 'width=854, height=480, resizable'}
            );
```

Result is empty feed and `TypeError: getTopWindow(...).gBrowser is undefined feedview.js:53:5` in console.

**Comment by tanriol** [comment]
Hmm... never tried, maybe it's possible.

**Comment by tanriol** [comment]
Not applicable to WE.

**Comment by vovkkk** [comment]
> Not applicable to WE.

Does it mean that new version of Brief will be able to work in separate window without tabbar and urlbar? like webapp in Chromium?

**Comment by tanriol** [comment]
This means that the WE version does not touch browser internals and if something does not work, that will be a Firefox bug, not a Brief one.

I've tried right now and Brief did actually work in such a window, but I'm not going to test that regularly.
