### ISSUE TITLE
Can you get this signed?

### ISSUE THREAD

**Issue by RyanTG** [ancestorak/brief#165]
Can't install this in FF 41+, because they don't allow unsigned addons.

I don't know much about the signing process (though mozilla claims it's simple).

**Comment by tanriol** [comment]
@RyanTG, Brief 2.0.1-signed is currently published. Are you still on the previous beta?

Anyways, for Firefox 42 we'll need a fixed build. No, I cannot publish it, only @ancestorak can and I haven't heard from him for months.

**Comment by RyanTG** [comment]
Thanks @tanriol. I actually hadn't tried installing on desktop Firefox - only on mobile Firefox, and haven't had any luck. But I just looked and it seems that the desktop version will install once I restart the browser. But I keep running into issues on mobile.

**Comment by tanriol** [comment]
@RyanTG, no mobile support yet. Hasn't tried, but AFAIK several required techologies are not available there at all.

**Comment by RyanTG** [comment]
Ah, thank you. It seems strange to me that mobile firefox doesn't have built-in RSS support. But there's clearly a lot I don't know both about RSS and about browsers (especially given that chrome can't render RSS files, either).

Closing.

**Comment by tanriol** [comment]
Not sure about the RSS support... well, for one point the Brief user interface and integration in Firefox is built on XUL, which is a Firefox-only HTML-like language - which is being gradually deprecated and, AFAIK, is not available (at least for integration) in mobile Firefox. It is likely possible to implement support, but Brief is not yet there.
