### ISSUE TITLE
Firefox 42.0/Linux: Brief does not display after import

### ISSUE THREAD

**Issue by jibe-b** [ancestorak/brief#166]
Hi!

I installed Brief as addon to Firefox 42.0 on linux.
The import of bookmarks+livemarks (as well as bookmarks and livemarks separated) in OPML format works. I can see it as I can export them from Brief to OPML.

But nothing appears on the chrome://brief/content/brief.xul page.

Is there something I should configure?

**Comment by tanriol** [comment]
Brief is broken on Firefox 42. Summoning @ancestorak to release the fix finally!

**Comment by NgoHuy** [comment]
I debug and this's result:

`A coding exception was thrown and uncaught in a Task.

Full message: TypeError: calling a builtin Map constructor without new is forbidden
Full stack: LivemarksSync@resource://brief/Storage.jsm:1698:27
TaskImpl_run@resource://gre/modules/Task.jsm:330:41
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1`

I don't know javascript, then have no idea to fix it :(

**Comment by tanriol** [comment]
This is known and already fixed in the master branch. Unfortunately, @ancestorak is the only one who can publish the fixed version on AMO. If he does not come back, I'll probably have to fork and publish it under another name.

**Comment by ancestorak** [comment]
Don't worry, I'm back, I'll be releasing the update tomorrow.

**Comment by NgoHuy** [comment]
thank you very much

**Comment by jnachtigall** [comment]
@ancestorak Thanks. But please: could you share the AMO account with a few more people? Or add users there. I do not see a reason to give others push permission on github, but not access to AMO. This is just slowing down the whole project.

Jesus, I've been waiting for this fix for 2 weeks now, albeit the fix was already committed but just not released yet. Have already been looking for rss alternatives.

**Comment by Ngamer01** [comment]
To be fair, there is a lot coming down the pipe in the Mozilla ecosystem that involves XUL being killed off.  That, the combination of Firefox rapid release, the coming e10s, real life, and actually coding Brief is tough.  Even if ancestor is silent doesn't me he's just sitting on his hands.  Perhaps there is merit in promoting tanriol to be able to push updates to AMO whenever ancestor is busy/unavailable, but threatening ancestor isn't going to get your problems fixed any faster, jnach.

**Comment by tanriol** [comment]
@Ngamer01, the "real life" point seems to be the primary one in this case. Anyway, the next update will be submitted for review tomorrow or maybe the next day.

And yes, you're right, e10s and XUL are the next roadblocks we're trying to drive around.

**Comment by jnachtigall** [comment]
@Ngamer01 sorry for sounding harsh, no hard feelings. Brief is a good addon :) Thanks to all who are involved. :heart:

**Comment by silentbrains** [comment]
Thank you for the update!

**Comment by RaveBomb** [comment]
I've got 2.1.1.1-let-fixed under FF 42 and I'm still unable to add new RSS feeds. 

I get the error: 
TypeError: this.sink is null 
in the Browser Console when I try to add a feed

**Comment by NgoHuy** [comment]
I add new feed normally, are you sure that feed in `Subscribed Feeds` folder ?

**Comment by tanriol** [comment]
@RaveBomb, could you please check whether you have this bug for a single feed or for any feed and provide the feed URL if the bug is feed-specific? I've never seen this bug yet.

**Comment by RaveBomb** [comment]
This is what I've done: 

removed Brief. 

restarted FF 

opened about:config

reset extensions.brief.*  to their default value of "" 

reinstalled Brief from the about:addons page 

restarted FF 

Updated Brief from 2.0.1 to 2.1.1.1 

restarted FF 

Opened Brief. 

No feeds are available. 

Opened developer console. 

Opened Brandon Sanderson's webpage
http://brandonsanderson.com/

Clicked the RSS icon in the upper right corner of the screen. Am presented with the "Subscribe with Live Bookmarks" dialogue. 

Select my "Feeds" folder and click Subscribe. 

TypeError: this.sink is null

No feeds are shown in Brief. 

Open new tab and navigate to 
http://www.michaelastackpole.com/

RSS feeds selection is in the bottom right corner of the webpage: 
http://www.michaelastackpole.com/?feed=rss2

Am presented with the "Subscribe with Live Bookmarks" dialogue. 
Select my "Feeds" folder and click Subscribe. 

TypeError: this.sink is null

No feeds are shown in Brief. 

http://i.imgur.com/YuQKWXR.png

**Comment by RaveBomb** [comment]
I am willing to entertain the idea that I've got something fuxed up with my install somehow.  Any suggestion on how to best unfux myself are welcome.

**Comment by tanriol** [comment]
So you reset all config... what bookmark folder did you add the feed to? Brief should have created a completely new "Subscribed Feeds" (maybe translated, depends on the locale) folder after such a wipe-and-reinstall.

The error "this.sink is null" seems to be unrelated to this according to the filename in the right column. Actually, the exception above in a file starting with `FeedWrit` seems to be more suspicious :-)

**Comment by RaveBomb** [comment]
I found the new folder. I'm thinking that when I first installed Brief, I must have moved/renamed it. For this reinstall/rebuild, I was trying to duplicate my older setup, but had missed that Brief was looking at a diff folder than I was trying to use. 

ID10T error.  :)    Things are working correctly.   Thanks for your assistance.

**Comment by tanriol** [comment]
Closing issue as fixed in `2.1` series

**Comment by jibe-b** [comment]
Thanks for the release, it's been working for the last few weeks.
