### ISSUE TITLE
Website (http://brief.mozdev.org/) links to outdated version

### ISSUE THREAD

**Issue by jnachtigall** [ancestorak/brief#167]
The website (http://brief.mozdev.org/) seems outdated. There is a button "Install Brief 2.0".

I would propose just to have an "Install" button which links to https://addons.mozilla.org/de/firefox/addon/brief/ always. Then you do not have to update with each version.

**Comment by tanriol** [comment]
Wow, direct link to an xpi... @ancestorak, are we going to update that site and how? Maybe setup a github.io site instead?

**Comment by nohamelin** [comment]
AMO lets you link directly to the xpi of the latest reviewed version of any add-on, using:

https://addons.mozilla.org/firefox/downloads/latest/brief

**Comment by tanriol** [comment]
@ancestorak, I've removed the links to http://brief.mozdev.org/ from the addon profile because the website is getting outdated and I have no access to update it.

**Comment by Keith94** [comment]
These files also need updating: `install.rdf` and `README.md`

**Comment by tanriol** [comment]
Will switch to Github Pages in #281.
