### ISSUE TITLE
All feeds are missing

### ISSUE THREAD

**Issue by micnic** [ancestorak/brief#168]
I have a strange issue, some time ago the feed list in the left side disappeared, but the feed items were still updated and I could read them, until they disappeared too, I had some problems with the OS and thought that it may be the source of the problem, removed the Firefox profile, created a new one, synced my bookmarks, but the feeds are still missing, then I tried to debug the `chrome://brief/content/brief.xul` tab and got the following error:

> A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

> Date: Mon Dec 07 2015 15:07:35 GMT+0200 (EET)
Full Message: TypeError: calling a builtin Map constructor without new is forbidden
Full Stack: LivemarksSync@resource://brief/Storage.jsm:1698:27
TaskImpl_run@resource://gre/modules/Task.jsm:330:41
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1

**Comment by tanriol** [comment]
@micnic, this is a well-known error fixed in Brief 2.1. Please update to the latest release. 

Please note that after creating a new profile you will probably need to find the new Brief "Subscribed Feeds" folder and move your feeds there (or set the home folder ID determined using other extensions).
