### ISSUE TITLE
Syncing...

### ISSUE THREAD

**Issue by Anandajoti** [ancestorak/brief#169]
This is just a suggestion, but it arises because of a real life issue: it would vastly improve Brief if we were able to synch across devices. At present when I go to Brief on my laptop I often find scores of posts which I have read on my desktop but which are still marked unread on the laptop, and then there are the new and actual unread mixed in, and cannot easily be distinguished from those read earlier. Don't exactly know how much would be involved but syncing would solve this of course.

**Comment by tanriol** [comment]
Already suggested, see #93 for discussion. Needs a nontrivial amount of time to implement.
