### ISSUE TITLE
Opening the "what's new" webpage after updating Brief needs be fixed or removed

### ISSUE THREAD

**Issue by nohamelin** [ancestorak/brief#173]
After updating Brief to 2.2b1, I got a new tab with a "Page not found" site:
http://brief.mozdev.org/versions/2.2b1.html

This 'feature' has been broken since many releases ago, as the official website is not updated anymore. Maybe the url can be changed to:
https://github.com/ancestorak/brief/releases/tag/v2.2b1 

If not, this whole behaviour should be removed.

**Comment by nohamelin** [comment]
For the latter, I could submit the patch, it's fairly direct.

**Comment by tanriol** [comment]
I wonder whether anyone actually wants to read them on every update. At least for me they're completely useless in any case.
Maybe we should integrate them into the Brief tab itself. Or just remove.

**Comment by nohamelin** [comment]
The lastVersion preference was being used only to support this feature, so it could be removed too.

**Comment by tanriol** [comment]
I've intentionally kept it for now. I suppose we may later need to introduce some way of telling users about the new features and it will be useful.
