### ISSUE TITLE
Long item name overflows

### ISSUE THREAD

**Issue by Keith94** [ancestorak/brief#177]
Item names can exceed the width of the container and cause a horizontal scroll bar. Not sure if it's better to set a maximum width for it?

Example feed: http://predb.me/?cats=dox&rss=1

![snag 2016 01 25 02 59 18](https://cloud.githubusercontent.com/assets/5490615/12549099/bf8662fc-c30f-11e5-9465-2a23e7bf6a74.png)

**Comment by tanriol** [comment]
And that's probably not the only point in the styling that needs fixing. Thank you for reporting, will ensure they are correct for the next overhaul.

**Comment by tanriol** [comment]
Should be fixed with 3681d07.
