### ISSUE TITLE
URL starting with "brief://" gives "The address was not understood" when trying to subscribe with Fx Dev Edition

### ISSUE THREAD

**Issue by jnachtigall** [ancestorak/brief#185]
Using Firefox Developer Edition (Fx 46) I get "The address wasn't understood" when I try to subscribe to any feed:

Just go to https://github.com/ancestorak/brief and click the "Subscribe to this page" button in the Fx toolbar.

Then on the following page choose "Brief" and click "Subscribe".

![2016-02-08 15_01_13-recent commits to brief_master - firefox developer edition](https://cloud.githubusercontent.com/assets/3307404/12887559/7047e60e-ce75-11e5-83b1-e5ef5e27f7da.png)

The Firefox loads the following URL:
`brief://subscribe/https%3A%2F%2Fgithub.com%2Fancestorak%2Fbrief%2Fcommits%2Fmaster.atom`

And shows this error:
![2016-02-08 15_00_10-problem loading page - firefox developer edition](https://cloud.githubusercontent.com/assets/3307404/12887575/7e366f10-ce75-11e5-9e0a-ccf72bdad91b.png)

I know there are workarounds, so I could still manage to subscribe after some fiddling. But would be nice if the above would work too.

**Comment by nohamelin** [comment]
It's specific to having e10s (multi-process Fx) enabled.

**Comment by tanriol** [comment]
Using Nightly, I cannot even get this page to load under e10s. Certainly needs fixing.
/me enables e10s in the main development profile.

**Comment by MichaelEischer** [comment]
Seems like this is going to be fixed in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1095484#c16

**Comment by jnachtigall** [comment]
Interestingly, the feed is actually successfully added after "The address was not understood" is shown. So despites this very awkward "UX" here, it works ;)

**Comment by tanriol** [comment]
Should be fixed in 2.3b1, closing.
