### ISSUE TITLE
Brief shows blank screen on firefox developer 48.0a2

### ISSUE THREAD

**Issue by mailtowim** [ancestorak/brief#192]
Since Firefox developer edition has been updated to 48.0, the extension Brief stopped working.
When you want to see the new feed messages, you can find the correct number of new messages on the left side, but the right side of the screen keeps blank. Reverting firefox to an earlier version fixes the problem.

**Comment by tanriol** [comment]
Sorry, I've completely forgotten about this problem. Should be already fixed in git, I'll release a new version in a day or two.

**Comment by Ngamer01** [comment]
Firefox 48 has been pushed to the beta channel which means Brief no longer works in the beta channel.  Are you still trying to get the update together, tanriol?  I would try to install Brief from the master git, but the extension I was using for that has stopped working in beta too.

**Comment by Keith94** [comment]
It's easy to install it, just by downloading the master files and adding them to a new ZIP archive (with WinRAR or something) while changing the extension from zip to xpi. I made one here if you like: https://mega.nz/#!W9pFnKiA!GbZVeQ5Axbvo1rZdY4yDFpfR9hwuOdRCjUx6qJ6Y0M4

**Comment by tanriol** [comment]
Sorry, dropped out a bit. Will try to release it today.

**Comment by tanriol** [comment]
Uploaded both `2.2.2rc99` (beta) and `2.2.2` (awaiting review at the moment). Closing.
