### ISSUE TITLE
Opml file cannot be imported

### ISSUE THREAD

**Issue by Ikaaris** [ancestorak/brief#193]
Hi all, 
I have exported my RSS flows in an opml file with Brief 2.2.1 in Firefox 46.0.1 in Ubuntu Mate. 
Now I'm trying to import this file in Brief 2.2.1 in Firefox 46.0.1 in Windows 10. 
Nothing happens
There is not error message. 
I have tried to import the file multilple times. 
The issue is that the RSS flows do not appear in Brief. 
I have attached the opml file to this message (and changed the extension from .opml to .txt because it's impossible to upload with .opml extension
[Brief.txt](https://github.com/ancestorak/brief/files/276542/Brief.txt)
) 
Thanks in advance for your help

**Comment by tanriol** [comment]
Importing this file works mostly OK for me (except for the fact that one feed is listed three times in the file) on Firefox 46 / Linux. Cannot test on Windows right now, will check when possible.

**Comment by Ikaaris** [comment]
So strange that one of the 3 feeds is listed 3 times in your browser because Brief which is installed in Ubuntu contains 3 different feeds only. 
Normally you should see RSS flows of the 3 following websites : www.techno-science.net, http://www.unificationfrance.com and http://www.gratilog.net
Anyway, so I'm waiting for your answer.
Thank you very much for your answer

**Comment by Ikaaris** [comment]
Good evening Tanriol, 
Can I help you to find the origin of this issue ? 
For example, I can provide you extra logs from my computer. 
I have understood that you do not have any access to Windows at the moment.  
So perhaps you can ask me to do some tests then I will send you back the trace, the log and so on. 
Please let me know your concerns. 
Thank you.

**Comment by Ikaaris** [comment]
Hi Tanriol, 
To tell you that I just installed the last version (2.2.2) but the bug still exists. 
I can provide further information regarding my to help for solving this issue. 
Thanks.

**Comment by Ikaaris** [comment]
I found the origin of the issue. 
The file was properly imported in my administrator session without any issue whereas it's impossible to import the same for my standard user. So, I'm going to change my clearances, then do the import of the file and finally, remove adminstrator rights of my standard user.

**Comment by Ikaaris** [comment]
I found the origin of the issue. 
The file was properly imported in my administrator session without any issue whereas it's impossible to import the same for my standard user. So, I'm going to change my clearances, then do the import of the file and finally, remove adminstrator rights of my standard user.

**Comment by Ikaaris** [comment]
No... this solution does not work ! :-(

**Comment by Ikaaris** [comment]
This solution does not work !

**Comment by MichaelEischer** [comment]
I am able to import your opml file on Windows 8.1 with Firefox 48 and Brief 2.2.2. My assumption would be that your browser profile is somehow damaged.

Can you manually add RSS feeds to Brief?
Do the feeds show up in the Brief home folder (click Organize (the between refresh and options) in the Brief tab)?
Does your profile folder contain a brief.sqlite? Does it inherit its file permissions from the profile folder?
Close firefox, rename brief.sqlite to brief2.sqlite, start firefox again. Brief should reinitialize the feeds list after a short delay. The new brief.sqlite should have correct file permissions.
Can you remove two of the three duplicated entries for techno-science from the opml and try importing again?


The reason why one feed is contained three times in the opml seems to be that you have three bookmarks for it in the Brief home folder.
What definitely is broken, is correctly handling the import of duplicated feeds in brief. However, brief is adding the feeds to often in contrast to your problem.

**Comment by bdcomp** [comment]
Using an online [OPML generator](https://opml-gen.ovh/) I created an OPML file.
Trying to import it, I got this error:
`Brief cannot import feeds because of an invalid file format. The XML file isn't well-formed.`

**Comment by tanriol** [comment]
@bdcomp This OPML generator generates incorrect files. It does not escape the XML special characters(`>`, `<`, `'`, `"`, `&`) in the URLs.

**Comment by bdcomp** [comment]
Any suggestion for a working online OPML generator?

**Comment by tanriol** [comment]
No suggestions, but you can fix your file manually in something like Notepad by replacing in the last URL `&` with `&amp;`

**Comment by tanriol** [comment]
Closing this stale issue. I'll look at #319, however.
