### ISSUE TITLE
RSS feed name

### ISSUE THREAD

**Issue by regisfr** [ancestorak/brief#195]
Hi,

RSS feed name displays only 16 characters (All items, Today).

Example: « Actu-Environneme**nt** » _(18)_ is displayed « Actu-Environneme » _(16)_

If RSS feed name is composed of several words is worse, last word is truncated.

Example: « La Maison **Passive** » _(17)_ is displayed « La Maison » _(9)_

20 characters seems a good compromise.

Regards,
Régis

**Comment by MichaelEischer** [comment]
Which feed name do you refer to? The sidebar, the feed header, the feed name inside each entry of All items/Today?
Can you post a screenshot of the cropped feed name? For me the limit at all three occurrences of the feed name is at least 24 characters or even much larger.
As far as I can tell, the feed name is cropped automatically by firefox to use all the available space. Thus I doubt that there's much that can be done about the cropped feed names. A fixed character limit won't work as width of the text depends on the actual characters.

**Comment by regisfr** [comment]
RSS feed name inside each entry of All items/Today.

![brief](https://cloud.githubusercontent.com/assets/11314283/17522666/2ffd4616-5e58-11e6-8c5d-0bb33bfd9e1a.png)

**Comment by MichaelEischer** [comment]
Oh, I've forgotten about the headline view. I've added the missing feed name shortening in the referenced pull request.
However, one could still debate how much space should be used for the feed name.

**Comment by regisfr** [comment]
>  However, one could still debate how much space should be used for the feed name.

Of course.

**Comment by MichaelEischer** [comment]
> Where post enhancement requests ?
Just create an issue for them.

**Comment by regisfr** [comment]
Thanks.

**Comment by regisfr** [comment]
Thanks Denis.

Options > Options > Customize
`.headline-feed-name {
    white-space: nowrap;
    text-overflow: ellipsis;
}`

This is the right method ?

**Comment by tanriol** [comment]
@regisfr I don't exactly understand your question, but yes, you can do it in this way right now. I'll be releasing Brief 2.3 in a week or two, however, so you can just wait a bit :-)

**Comment by regisfr** [comment]
> but yes, you can do it in this way right now

That was my question.

Thanks for your work.
