### ISSUE TITLE
Make sure Brief works with e10s (electrolisys, multiprocess) enabled Firefox

### ISSUE THREAD

**Issue by mayhemer** [ancestorak/brief#207]
In particular, brief:// URLs won't load from the content process.  By default, we don't register protocol handlers in content processes.

There are APIs provided by Firefox to register custom protocol handlers in content process and to communicate between chrome and child processes.

**Comment by tanriol** [comment]
@mayhemer, thank you for the reminder. Issue #81 about e10s really needs some attention :-)

A rough status:
 - Brief mostly works on e10s-enabled Nightly (I'm using this combination).
 - brief:// URLs don't load, subscribing via Live Bookmarks working correctly. If you know the API that I need to use to implement it for e10s, please share.
 - Brief loads its tab, including all news items, in the chrome process. Fixing this will be a bit nontrivial.

Closing this bug. If you have any input, please welcome to #81.

**Comment by mayhemer** [comment]
Maybe this could help:

https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK

Also https://addons.mozilla.org/en-US/firefox/addon/donottrackplus/ addon may be an example of how to register a protocol on child (lib/protocol.js and lib/main.js).
