### ISSUE TITLE
Use requestAnimationFrame() for smooth scrolling

### ISSUE THREAD

**Issue by ancestorak** [ancestorak/brief#21]
This is the best practice and reduces stutter.

**Comment by tanriol** [comment]
Closing this in favour of #128. IMO, Brief should not take over scrolling, especially taking into account that we take over only *some* scrolling, but not, e.g., PageUp/PageDown or mouse wheel or middle button scrolling. Let's allow Firefox to manage scrolling as it's browser's job.
