### ISSUE TITLE
Brief 2.2.2 RSS feed not working !?

### ISSUE THREAD

**Issue by galuel** [ancestorak/brief#211]
[This RSS](http://tcrouzet.com/feed/?cat=-18%2C-15%2C-278) doesn't work with Brief 2.2.2 But it is [validated by W3C](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ftcrouzet.com%2Ffeed%2F%3Fcat%3D-18%2C-15%2C-278#l149)

So I don't know how to fix it !? If I manually add the RSS field in the Brief bookmark folder, it seems it does not recognize it as a feed... Thank you for your answer (or fix)

**Comment by MichaelEischer** [comment]
That feed is quite unusual in that it overwrites the default feed preview in Firefox. This prevents Brief from offering the correct subscribe option. There's currently no other convenient way to subscribe to a RSS feed. 

As Brief uses Livemarks to represent the RSS feeds, creating a normal bookmark doesn't work. Sadly the only way for a user to create Livemarks is using the feed preview.

There are however two possible workarounds:

Using the Options > "Import Feed..." function (in the Brief tab). Just import this file: 
[tcrouzet.txt](https://github.com/ancestorak/brief/files/522860/tcrouzet.txt).

The second possibility: Open the following URL. It tells Brief to subscribe to the RSS feed with the given URL. The later part is just an encoded version of RSS feed's URL. Open a new tab and paste the link there. (If you are using Firefox Nightly / Developer Edition you must temporarily disable E10S for the link to work.)
brief://subscribe/http%3A//feedpress.me/blog-crouzet%3Fcat%3D-18%2C-15%2C-278

**Comment by galuel** [comment]
Thank you for that solution, that works perfectly ! I gave the information to the blogger who owns this site.

**Comment by tanriol** [comment]
Works for me now, so seems to have been by the feed owner. Closing.
