### ISSUE TITLE
Missing support for e10 multiprocess mode

### ISSUE THREAD

**Issue by cryptomilk** [ancestorak/brief#218]
This addon prevents Firefox from turning on support for multiprocess windows. Please add support for e10.

Thanks

https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by tanriol** [comment]
Well, not exactly missing. Brief does currently work almost correctly with e10s. However, the Brief tab is loaded in the main process which is bad for performance and responsiveness. Fully porting it to e10s requires a UI rewrite (XUL is not available in content processes) and is being tracked in #81.
