### ISSUE TITLE
Feed Folder in Bookmarks

### ISSUE THREAD

**Issue by ArSa-Apps** [ancestorak/brief#219]
Hi,
if one chooses to sync bookmarks across devices, for every single device brief should be set up from scratch. More importantly, every single device creates an identical folder called "Subscribed Feeds" to store the feeds. Shouldn't this add-on always use the same folder?

Cheers,
A.

**Comment by hackhowtofaq** [comment]
Is there a reason for this happening?

**Comment by tanriol** [comment]
In my opinion, Brief should use the same folder by default, but keep the ability to use different folders if desired. However, I lack time right now to implement this.

**Comment by hackhowtofaq** [comment]
You could break the job in two parts and implement the first one which should be easy (same folder by default) ... I could help if you guide me

**Comment by tanriol** [comment]
Due to significant internal changes, closing in favour of #279.
