### ISSUE TITLE
New feed folder empty when synchro

### ISSUE THREAD

**Issue by galuel** [ancestorak/brief#222]
When installing Brief on another PC (Ubuntu / Firefox), and then do the Firefox sync. Brief always creates a new empty bookmark feed folder, and so shows no RSS feeds. The original bookmark feed folder is well synchronised with all the RSS sources in it.

In the original PC then, the synchro will create also the new empty bookmark feed folder I don't care...

How can I link the original bookmark feed RSS folder to Brief ? Could it be possible to take account the Firefox sync function (which works very well), in order to not create new empty bookmark folders that is not necessary !?

Perhaps a solution would be that brief no creates new bookmark folder, better asking the user to tell him which bookmark folder will be used (created by the user so, not by Brief itself).

**Comment by silvio** [comment]
Duplicate to #156

**Comment by tanriol** [comment]
Closing due to the sync mechanism changes; will continue Sync work in #279.
