### ISSUE TITLE
Some feeds update with items I've read

### ISSUE THREAD

**Issue by Brig9902** [ancestorak/brief#228]
Brief is set to update every hour. I've noticed a few of my feeds consistently retrieve items that I've already read. Here's an example:

https://apod.nasa.gov/apod.rss

Is this an issue with Brief or is it with the feed/website?

Thanks

**Comment by nohamelin** [comment]
Sometimes it happens when an item has been edited in some ways by the website. Try enabling the "Don't mark changed items back as unread" option in the properties window of that feed (right-clicking on it in the lateral pane).

**Comment by Brig9902** [comment]
I think that solved the problem. Many thanks.

**Comment by nohamelin** [comment]
Sure. You can close this ticket, by the way.
