### ISSUE TITLE
[Compatibility Request] Consider adding Seamonkey Compatibility to Brief

### ISSUE THREAD

**Issue by Ngamer01** [ancestorak/brief#229]
Since Firefox will be pulling the trigger soon on "legacy" addons when e10s get enabled by default in Firefox 53 (tracked in Issue #81), my suggestion is to consider adding Seamonkey support to Brief for users that migrate off Firefox because of Firefox 53 (and don't want to stay on Firefox ESR delaying the inevitable by one more year).

Some work in adding support was started in pull request #133, but it would be cool to have full support added to Seamonkey.  It would also be cool in case the e10s version of Brief isn't possible on e10 Firefox (53+).

I'd hate to lose my favorite RSS extension so I figured to make a request before it's too late.  We can use this thread to discuss the request so that we don't have to bog down any work done in pull request #133.

**Comment by tanriol** [comment]
What limitations does SeaMonkey compatibility cause? Does SeaMonkey support WebExtensions and/or embedded WebExtensions? I'm ok with considering this possibility, but (a) I don't have enough time, (b) I'm going to keep using Firefox and thus migrate to the new system in the time I do have. I really hope that SeaMonkey and Firefox compatibility in the same codebase will be possible.

**Comment by Ngamer01** [comment]
I apologize for the late response, but currently Seamonkey still uses XUL/Gecko.  I'm not an extension dev, so I have no idea what all will be needed for a Seamonkey port, but Seamonkey devs will have to figure out if they will want to continue using XUL/Gecko, switch with Firefox to Webextensions/Servo, use something else, or end the project.

You can follow news about Seamonkey here (also checkout Seamonkey General there): http://forums.mozillazine.org/viewtopic.php?f=3&t=2973875

If you want to ask/test any future Seamonkey port, you can post something over here to see if anyone can be of help:  http://forums.mozillazine.org/viewforum.php?f=19

**Comment by tanriol** [comment]
Right now I'm porting the XUL components of Brief to (X)HTML5, which I hope is supported everywhere and will be supported for the foreseeable future. I hope to have a e10s-compatible bootstrapped extension in something like two weeks, with possible minor functionality loss. However, this is only an intermediate step and I'm looking into the options wrt WebExtensions as I don't personally want to leave Firefox.

**Comment by tanriol** [comment]
Looks like the WE APIs should not require any special support. Wontfix for legacy, not needed for WE, closing.
