### ISSUE TITLE
v.2.3.0 (support, multiple issues)

### ISSUE THREAD

**Issue by d-stark** [ancestorak/brief#237]
Hi,

since last update to 2.3.0 brief doesn't work anymore in FF 52.1.1 (32-Bit). It doesn't find the file under chrome://brief/content/brief.xul and ends with an error message 'file not found'.

In FF 53.0.2 (64-Bit) it loads new Feeds but doesn't show the list of subscribed feeds on left side.

Also in both browsers options page shows only the main options.

I hope for fast troubleshooting, because it is a great add-on.

Regards, Daniel.

**Comment by tanriol** [comment]
> since last update to 2.3.0 brief doesn't work anymore in FF 52.1.1 (32-Bit). It doesn't find the file under chrome://brief/content/brief.xul and ends with an error message 'file not found'.

What do you do to open that page? Brief 2.3.0 no longer has `brief.xul`, it should always open `brief.xhtml` instead.

> In FF 53.0.2 (64-Bit) it loads new Feeds but doesn't show the list of subscribed feeds on left side.

Sounds strange, will check. You're on Windows, aren't you?

> Also in both browsers options page shows only the main options.

There's only one options page since, IIRC, 2.0. What options are you missing?

**Comment by tanriol** [comment]
> In FF 53.0.2 (64-Bit) it loads new Feeds but doesn't show the list of subscribed feeds on left side.

Also, does this mean "nothing in the sidebar" or "no sidebar at all"? If the latter, you may have accidentally hidden it... if that's the case, there should be a button along the left edge labelled "reveal the sidebar".

**Comment by plucid** [comment]
I can repro the "Firefox can’t find the file at chrome://brief/content/brief.xul" error.  Running on FF 53.0.2.  I checked my most recent backup brief@mozdev.org.xpi (v2.2.2 from Jun 11, 2016) against the new v2.3.0 that got downloaded today.  There is, indeed, no content/brief.xul in the new .xpi.  There is still a reference to it in chrome.manifest:

```
content  brief  chrome/content/ remoteenabled=yes remoterequired=yes
skin  brief  classic  chrome/skin/

resource brief-content  defaults/data/
resource brief          modules/

overlay  chrome://browser/content/browser.xul  chrome://brief/content/brief-overlay.xul

style  chrome://global/content/customizeToolbar.xul  chrome://brief/skin/overlay.css
```
I know nothing about FF addons, but that clearly seems wrong.  I'd try removing the line, but I doubt I can do that if add-ons are all signed now.

**Comment by tanriol** [comment]
@plucid Oh, a pinned tab, that explains it. It still tries opening the old Brief URL, not the new one. You can replace `xul` with `xhtml` in the address or just close this Brief tab and open a new one using the Brief button / shortcut. Sorry, there's no automatic redirection at the moment.

> There is still a reference to it in chrome.manifest

There's a reference to `brief-overlay.xul`, which is still present, but not to `brief.xul`.

**Comment by tanriol** [comment]
Added [a FAQ entry](https://github.com/ancestorak/brief/wiki/FAQ#after-updating-to-v23-firefox-cant-find-chromebriefcontentbriefxul) about this error message.

**Comment by d-stark** [comment]
Hi Denis, thank you for advising, with your help I could solve my problems. 
I have brief always opened in a window and didn't know there is a new address.

Also the sidebar is back.

The thing with the option pages was a misunderstanding. I couldn't find them since they were in the sidebar which was gone.

Thanks again.

**Comment by tanriol** [comment]
@d-stark, glad to hear, closing the report.
@plucid, if Brief is not working, feel free to comment, but it really should after you open the correct URL.
