### ISSUE TITLE
Error: Impossible find the file chrome://brief/content/brief.xul

### ISSUE THREAD

**Issue by TearsDuct** [ancestorak/brief#245]
Hi,
I'm on FF 53.03 x64 and Win10 CU.
Few days ago your addon stop working. I tried to remove/install the addon and disable all the other addons but in my Firefox appears always the error "impossible to find the file brief.xul". I didn't install other addons when the issue started.
![immagine](https://cloud.githubusercontent.com/assets/28859579/26300595/d453f5c2-3ede-11e7-8e05-53f433c7db36.png)

**Comment by tanriol** [comment]
The main Brief page has been moved from `brief.xul` to `brief.xhtml`. Just closing the Brief tab and opening a new one using the Brief button should be enough.

**Comment by TearsDuct** [comment]
Thank you, it worked!
