### ISSUE TITLE
New Items not Shown

### ISSUE THREAD

**Issue by jomoncon** [ancestorak/brief#246]
This morning, I added several new feeds. When I subscribed, they all showed new items. None of them are showing any new items in the feed sidebar, even after refreshing. Here are some of the websites:
http://www.chickettes.com/
http://www.chalkboardnails.com/
http://tenlittlecanvases.com/

I've never had this problem before.

**Comment by jomoncon** [comment]
Added info:
When I subscribed to this website, the count on Brief showed a new number, then it immediately disappeared: http://www.blognailedit.co/   I didn't notice if it did that on the other websites.

**Comment by Gorfiend** [comment]
I've run into a similar issue. When adding a feed, it will show all the current items, but after that it will never update to show new items that were added after subscribing. Live Bookmarks for the feed were updating to show the new items properly. In my case for nicovideo mylist feeds such as:
http://www.nicovideo.jp/mylist/58976040?rss=2.0&lang=ja-jp&special_chars_decode=1

After debugging what brief was doing, it looks like the feed sets an update time, but it never changes, even when new items are added. Specifically, [at scripts/database.js:415 in pushUpdatedFeed](https://github.com/ancestorak/brief/blob/657b30abc69b06327cce307fe6e4418783ef2268/scripts/database.js#L415), "modified" was always getting set to the same value, which causes it to assume there was no update. Commenting out this line to always use "modified = Date.now()" allowed the feeds to update properly and show new items after a refresh.

**Comment by tanriol** [comment]
@jomoncon Did you have the setting to remove old items automatically enabled?

**Comment by jomoncon** [comment]
No I don't.

**Comment by tanriol** [comment]
I've tested all four and they successfully loaded new items on Brief 2.5.5. Do they work for you now?

**Comment by jomoncon** [comment]
Soime of them worked - some didn't. Thanks so much for all your help.
