### ISSUE TITLE
Add default fetch delay as an option

### ISSUE THREAD

**Issue by Keith94** [ancestorak/brief#247]
In the options window please add the pref `extensions.brief.update.defaultFetchDelay` as an option under the refreshing section. It may be useful to some users who want to refresh feeds quickly by setting the value to 0.

**Comment by tanriol** [comment]
Do you mean doing a quick refresh once or always refreshing as fast as possible?

**Comment by Keith94** [comment]
I kinda meant when "always refreshing", because by default the fetch delay is set to two seconds. So simply having a UI option to customize this wouldn't be bad.

**Comment by tanriol** [comment]
Ok, so most likely I'm not going to expose this setting for several reasons, at least for now. It's fine as an advanced one.

First, a feed reader is *not* expected to be manually activated every time. The "Update" button is a convenience, but not the primary way of operation. Background updates are more important.

Second, users *will* set it to 0 and then complain that pressing the button freezes the browser while it fetches everything.

Third, after fetching and parsing feeds is offloaded to a separate worker thread, I intend them to be updated as fast as possible. However, this requires a significant rework that's not ready yet.

**Comment by Freudentaumel** [comment]
Thank you for your engagement, tanriol. I wish you much power.

**Comment by Keith94** [comment]
@tanriol Thanks for the answer.
