### ISSUE TITLE
RSS subscriptions disappear

### ISSUE THREAD

**Issue by Kimed** [ancestorak/brief#249]
For several times during the latest month, Brief would reset itself to zero state. When I open Firefox and launch it, it answers "You haven't added any feeds yet". Sometimes it also creates a new empty "Subscribed Feeds" subfolder in Bookmarks Menu, even though an old one (or few) with the same name and containing feed links is already there. Today it didn't create one, instead it placed a newly created feed into one of my own custom bookmarks subfolder (adding other RSS link into it restored them as well in Brief). After restoring, Brief usually works normally for a couple of days, then resets itself again.

Right now I use 32-bit Firefox 54.0.1, yet it all started several updates ago (somewhere around 51, though can't say more spefifically).

**Comment by tanriol** [comment]
Have you restored bookmarks from a backup or done something like that? Installed some new bookmark-related add-ons?

**Comment by Kimed** [comment]
I tried restoring through "Show All Bookmarks->Import and Backup->Restore" and "Import Backups from HTML". Some of times it worked, other times it didn't (no error message of any kind, just Brief telling me that I still haven't subscribed to anything). When it didn't, it'd usually help to fill empty  "Subscribed Feeds" folders with contents of those  "Subscribed Feeds" folders that *had* one. Today was the first time that *nothing* of the above would work until it came to me to subscribe to a feed manually and see where in Bookmarks it lands. It landed into a folder where a subcategory of my regular bookmarks were; I copied the rest of feed bookmarks into that subfolder and they appeared in Brief as well.

I didn't use Brief's native import/export using OPML files, though I created one after my last restore; I'll see if it works better next time.

I do not have any other bookmark-related addons - at least none that would *claim* to be bookmark-related. If necessary, I might send you an exact list of all my addons, though that'd have to wait until Monday when I'm back at work - on my home computer I do not have problems with Brief.

**Comment by tanriol** [comment]
@Kimed Sorry, I was not clear. Restoring a backup *does* cause this problem as folder IDs change and Brief loses track of the root folder. My question was whether that's *the* reason or the feeds were lost for some other reason than a bookmark restore.

**Comment by Kimed** [comment]
I see. I was only restoring bookmarks as a consequence of feed losing, not prior to it.

**Comment by davimack** [comment]
Signed into a new Firefox yesterday.  Looked at feeds this morning on my usual device, went in to work & used the new work device, then came home to find I had no feeds in my Subscribed Feeds.  Not sure if this is a FF sync issue, or a Brief issue, but I've restored bookmarks from a backup and can't get Brief to recognize them.

**Comment by ramb4ldi** [comment]
I had the same issue as davimack. I had the pop saying 200 items in 20 feeds updated and then when I went to look at brief there was nothing, No subscriptions etc.

**Comment by tanriol** [comment]
Wontfix for the legacy version, fixed in the WE one.
