### ISSUE TITLE
[Linux] Firefox Nightly "Access to the file was denied"

### ISSUE THREAD

**Issue by joder666** [ancestorak/brief#251]
Brief stopped working out of the blue in Nightly for linux, on windows is still working fine.

When i clicked on the brief icon i get this error:

Access to the file was denied

The file at chrome://brief/content/brief.xhtml is not readable.

    It may have been removed, moved, or file permissions may be preventing access.

I already tried to re-download Nightly, delete the old folder and create a new one in my Home still no go.

I created a clean profile for Nightly, install Brief, still no go.

Lastly i tried to check the file permissions for "brief.xhtml" but that file is no where to be found.

**Comment by tanriol** [comment]
Are you performing any special tricks with a development install or so? I've seen this problem, presumably related to the new seccomp read filtering, and worked it around locally with `security.sandbox.content.level` pref set to 1.

**Comment by joder666** [comment]
When i 1st encountered the issue i had modified many settings in about:config. But as i said i created a new profile and leave it untouched, to make sure it wasn't  some setting i toggled messing things up.

Anyways i check out this one `security.sandbox.content.level` on windows  it is set to 3 as well as in linux.
I changed it to 2, did not work, setting it up to 1 fixes the problem.

**Comment by tanriol** [comment]
And you installed the addon by pressing the "Install" button on AMO, right?

**Comment by joder666** [comment]
Yes

**Comment by tanriol** [comment]
Ok, I'll debug this in a few days.

**Comment by tanriol** [comment]
This seems to be the Firefox [bug 1385891](https://bugzilla.mozilla.org/show_bug.cgi?id=1385891), so hopefully it should be fixed soon.

**Comment by tanriol** [comment]
Fixed upstream and already good in latest Nightly. Can exist in Beta for now, but will be fixed too. Anyway, this is not a Brief bug and the recommended workaround is setting the `security.sandbox.content.level` pref to 1.
