### ISSUE TITLE
FireGestures commands are no longer recognized by Brief

### ISSUE THREAD

**Issue by sleek22** [ancestorak/brief#253]
In the previous version of Brief, I could use FireGesture gestures to send key commands to Brief. In the latest version, they don't do anything.

For example, this command:

FireGestures.sendKeyEvent({key: "M" });

would send the letter "M" and mark an item as "read". Now, there is no response to this or any other FireGestures command.

**Comment by tanriol** [comment]
Are you talking about the latest released version, i.e. Brief 2.3.0? There were some changes related to shortcut processing, but I don't know off the top of my head what could cause this problem.

**Comment by tanriol** [comment]
Except for, maybe... does `FireGestures.sendKeyEvent({key: "m" });` work?

**Comment by sleek22** [comment]
Yes, the problem is on version 2.3.0 and yes, I've tried both lowercase and uppercase and it makes no difference.

**Comment by tanriol** [comment]
Closing this bug as FireGestures looks not migrating to WE.
