### ISSUE TITLE
After brief 2.4.0a1 update everything is empty now

### ISSUE THREAD

**Issue by cryptomilk** [ancestorak/brief#257]
Looks like brief got updated to 2.4.0a1 and it shows just a pretty much blank page now:

https://i.imgur.com/OcxIK5f.png

Firefox ESR 52.3.0 (64bit) on Linux

I'm not able to click on anything. If I click on Options nothing happens.

Please let me know how I can provide log or more details.

**Comment by tanriol** [comment]
Please try updating to 2.4.0a2, there's a fix for ESR (565c7791df39c120d5dc127795ab0557e4552fd0).

**Comment by cryptomilk** [comment]
I've updated to 2.4.0a2 and it works again. Thanks!
