### ISSUE TITLE
Unable to Subscribe to Some Feeds via Brief dev version (2.4.0a2)

### ISSUE THREAD

**Issue by eberhardweber** [ancestorak/brief#261]
I just moved to Brief to work with my Live Bookmarks (which have turned out to be a hassle with no .opml export built-in Firefox).

In the process of moving my bookmarks to Brief, I was unable to make Brief subscribe to a few of them. My issue seemed slightly different from #260 so I made a new bug report. Here are a few example feeds:

https://feeds.soundcloud.com/users/soundcloud:users:71232988/sounds.rss
https://wakingup.libsyn.com/rss

Especially the Soundcloud feeds seem to be problematic. I have tons of them and none of them can be subscribed to.

Edit: Interestingly, when I copypaste them into Brief's folder, they do work. It's just the subscribe part that doesn't activate.

**Comment by tanriol** [comment]
Unfortunately, Brief will have to stop working with Live Bookmarks in Firefox 57 as there's no Live Bookmarks API for WebExtensions yet. I'll have to rework the subscribe functionality too, so I'll try to make these work.

**Comment by tanriol** [comment]
The new subscription method works with these. You may also be interested in #5.
