### ISSUE TITLE
Brief extension freezes / hangs firefox

### ISSUE THREAD

**Issue by lcoulet** [ancestorak/brief#263]
Hi,
From time to time (dozen times a day) firefox just hangs and becomes unresponsive, the only way to recover is to kill firefox and then restart it.

Firefox 55.0.3 (32 bits) on Windows 7 Pro x64.
Brief 2.3.0 

I think it occurs when brief updates feeds, but not every time (I will do more testing to validate this).
When I deactivate or remove brief it doesn't hang anymore.

This is kind of a problem for me because Brief is the only usable feed reader I ever found (it's great actually, all other suck!) 

I removed Brief, deleted the brief sqlite database, then reinstalled brief and resubscribed to feeds. It did not solve the issue.

Am I the only one suffering this problem? 
Do you have any clue or suggestion?

Thanks for your support, and for this great feed reader.

**Comment by eberhardweber** [comment]
I'm pretty sure I get this as well with Brief 2.4.0a3 - I think the freezing started happening after I started using Brief. My browser doesn't hang for good though, just gets very slow for 2-10 seconds. Maybe I don't have as many feeds as you do? It's on the borderline of unresponsive during that time.

I'm on 55.0.3 (64-bit) with 4 content processes.

I was pretty sure before I read this post that the freezing had to do with Brief updating feeds as well, so I think we are pretty much clear now that this is what is going on.

**Comment by tanriol** [comment]
Have not seen this problem yet. This definitely should not happen, especially with an almost empty database. @lcoulet, any chance you could check the same feed list on another computer and/or share it?

**Comment by lcoulet** [comment]
Eventually I updated to Firefox 64-bits, and then it never happened again (even with only one content process). Closing the issue.
