### ISSUE TITLE
No OPML file is exported on FF55.0.3 (Brief 2.4.0a3)

### ISSUE THREAD

**Issue by eberhardweber** [ancestorak/brief#264]
I was wondering if this was a FF55.0.3 (64-bit) WebExtension limitation that the OPML file is never created when exporting feeds via "Options > Export Feeds..."?

The file saving dialog does pop-up, but when I press save, the "feeds.opml" file is not created. 

In case you can not yet do anything about it, is there an ETA for the export mechanism to work?

**Comment by tanriol** [comment]
Are you on Brief 2.3.* or development versions (2.4.*)?

**Comment by tanriol** [comment]
Works for me at least on Fx52 + 2.4.0a3, Nightly + 2.4.0a3 and Fx55.0.3 + Brief 2.3.0.

Please check whether you have permissions to create the file in the location you're trying to. If yes, please specify the Brief version, your OS name and version.

**Comment by tanriol** [comment]
Works for me on Linux 64-bit, Firefox 55.0.3, Brief 2.4.0a3.

**Comment by eberhardweber** [comment]
Sorry I only specified the Brief version in the issue title! Developmental version, 2.4.0a3, Windows 7 64-bit. Trying to save into my downloads folder.

**Comment by eberhardweber** [comment]
FF56 just came out, grabbed it from Mozilla's FTP. Can confirm that exporting now works with it. This may be a problem that is left in the trash bin of history...

**Comment by tanriol** [comment]
Ok, closing this bug.
