### ISSUE TITLE
Brief (2.4.0a3) creating extra browser.contentHandlers.types in FF about:config

### ISSUE THREAD

**Issue by eberhardweber** [ancestorak/brief#267]
I currently have 123(!!) instances of browser.contentHandlers.types (title, type, uri) in my about:config, all attributed to Brief (2.4.0a3). They all look the following: 

```
browser.contentHandlers.types.10.title;Brief
browser.contentHandlers.types.10.type;application/vnd.mozilla.maybe.feed
browser.contentHandlers.types.10.uri;chrome://brief/content/brief.xhtml?subscribe=%s
```

One should be enough, right? :D

**Comment by AraldoL** [comment]
Same here (not 123 instances but entries 6 to 17 are all identical Brief here, entry 0 is Yahoo and 1 to 5 are chrome: //browser-region/locale/region.properties). Entries 0 to 5 are gray, not resettable, should be default values.

**Comment by eberhardweber** [comment]
Today, I have 126. I've tried to think about what kind of action on my behalf could be creating them but so far I can't think of anything I've done that would possibly increase them. I was basically away from the keyboard for the most of the day, too.

**Comment by Mazzibig** [comment]
confirm. I try to delete instances from prefs.js manually, but strings with settings added after each restart of FF

**Comment by tanriol** [comment]
I don't know the exact reason of this error. Closing as wontfix because the legacy extension will go away with Firefox 57 release and the WebExtension version won't have access to these anyway.
