### ISSUE TITLE
Store no more than x latest items of each feed not working

### ISSUE THREAD

**Issue by 2SI3NX** [ancestorak/brief#270]
Ive set this to 300 and yet i have 2 or 3 latest items in each feed.
Also, another bug... **While** changing this number and say you are about to put '200'. The only way to change it is to highlight the number and replace it with 2, 0 , 0 but as soon as you start typing 2, thats when i lose all old feeds.
After setting it to 200, i can never get the old feeds i had back.

- I think putting an "Apply" button in settings so that the settings get confirmed after the user finishes setting them.
- Also, There should be another setting there to allow the user to get all their old feeds back till a certain date.

I removed all folders of my feeds and then re-imported them hoping i would get the older feeds back but i still get back 2 or 3 items within each feed.

**Comment by tanriol** [comment]
This should be working now. The settings are applied instantly, but the expiration process does not start while there is an Options or Feed properties window open.

You can return the items using the Trash folder context menu.
