### ISSUE TITLE
"TypeError: this.date.toLocaleFormat is not a function" on Nightly

### ISSUE THREAD

**Issue by simonlindholm** [ancestorak/brief#271]
Used [here](https://github.com/ancestorak/brief/blob/40e5d3a361d40ccaae5d60cf80dde748b197e8ae/chrome/content/feedview.js#L1278) and [here](https://github.com/ancestorak/brief/blob/e7ac2bf783b5f0fc2a80617a42356ea8a2d2f5db/bootstrap.js#L121), and was removed in https://bugzilla.mozilla.org/show_bug.cgi?id=818634. Breaks day-old entries showing up in the feed.

**Comment by tanriol** [comment]
Fixed in 7b00a50399671c5af62733078abbb8182c4425f7.
