### ISSUE TITLE
Updating the feeds

### ISSUE THREAD

**Issue by Freudentaumel** [ancestorak/brief#282]
Hello, tanriol,

First of all, thank you very much and praise from me for the fast migration to Web Extension. 

Where can I set the feeds to update faster than preset. 

Best regards
Gerhard

**Comment by tanriol** [comment]
Not exposed in the UI yet, but you can open a debug console with F12 on the Brief tab and enter something like
```javascript
Prefs.set("update.defaultFetchDelay", 250);
```

**Comment by Freudentaumel** [comment]
Where und how do I exactly enter the bug in the console exactly?

**Comment by tanriol** [comment]
F12, switch to the Console tab, in the bottom line. Paste and press Enter. Warning: when updating feeds with a short delay, Brief may be unresponsive.

**Comment by Freudentaumel** [comment]
Sorry, but I cannot realize.
Is there another way to report this bug?

**Comment by Freudentaumel** [comment]
I think I figured out how to make the entry. Is it so right?
==> https://www.pic-upload.de/view-34333547/Brief.png.html

**Comment by tanriol** [comment]
Exactly.
