### ISSUE TITLE
Items getting unread on refresh even if already marked them as read

### ISSUE THREAD

**Issue by will76** [ancestorak/brief#284]
Every time my feeds refreshes, it seems to fetch all items again and ignore the ones I already marked as read. This behavior did not happen before the WebExtension migration.

Note: I only have youtube feeds, such as https://www.youtube.com/feeds/videos.xml?channel_id=UCdGpd0gNn38UKwoncZd9rmA

**Comment by tanriol** [comment]
There's a setting to never mark modified items as read... and Youtube has the habit of marking items updated for no obvious reasons (probably due to new stars or even views(!)).

**Comment by will76** [comment]
That setting should be default, right?

Solved!

**Comment by tanriol** [comment]
It should probably be the default for Youtube feeds, but thete's no heuristics module to guess per-feed settings yet.

**Comment by tanriol** [comment]
See also #302.
