### ISSUE TITLE
Chronological sequence of the feed

### ISSUE THREAD

**Issue by Freudentaumel** [ancestorak/brief#285]
How can I put the feed list in chronological order? In the installation of Brief they were in chronological order and now no longer.

**Comment by tanriol** [comment]
What exactly is in an incorrect order? Are you talking about groups of entries that come from the same feed and have the same date?

**Comment by Freudentaumel** [comment]
I am talking about this list ==> https://www.pic-upload.de/view-34335576/Einstellungen.png.html

**Comment by tanriol** [comment]
Seem to be in chronological for me. Could you please describe in more detail?

What order do you want to see (newer on top or older on top)?

What order do you actually see (newer on top / older on top / random or no clear order)?

**Comment by Freudentaumel** [comment]
chronological = alphabetically

> What order do you actually see

In the meantime I have set up the alphabetical order manually.

**Comment by tanriol** [comment]
Ok, closing.
