### ISSUE TITLE
Can't Bookmarked items 

### ISSUE THREAD

**Issue by Patclash** [ancestorak/brief#287]
I just update to Brief 2.5 and all the bookmarked items are gone and I can't bookmark any new :(

**Comment by tanriol** [comment]
Seems to be fixed in 2.5.1.

**Comment by Patclash** [comment]
Can I recover the lost bookmarked item ?

**Comment by tanriol** [comment]
Not at the moment... if your bookmarked items are gone, this probably means that the whole database was lost and thus the only place that contains them is the old `brief.sqlite` database. I don't have import code for that right now.

**Comment by tanriol** [comment]
Opened #289 for that.
