### ISSUE TITLE
Adding a folder

### ISSUE THREAD

**Issue by Freudentaumel** [ancestorak/brief#288]
How do I add a folder?

**Comment by tanriol** [comment]
In the Organize mode, enter the folder name into any line with `...` and press Enter :-)

**Comment by Freudentaumel** [comment]
Sorry, I do not see any line with ". . ." in the Organize mode. Where have they been "hiding"? :-)

**Comment by tanriol** [comment]
In the end of every folder and in the end of the feed list.

**Comment by Freudentaumel** [comment]
https://www.pic-upload.de/view-34336397/Brief.png.html

. . . either we don't understand each other or I'm "blind." :-(

**Comment by tanriol** [comment]
Press the Organize button to switch the feed list to the organize mode. It should switch to orange background, make all folder titles editable and insert these lines :-)

**Comment by Freudentaumel** [comment]
Unfortunately, I find the ". . ." still not. Would it be possible to send me a screenshot? Maybe I'll miss something.

**Comment by Freudentaumel** [comment]
Now I found these items under the feed in my "Comments" folder. I haven't had an entry there in the last few days.

Is it possible that these items will only appear under a folder name if there is at least one entry there?

**Comment by Freudentaumel** [comment]
Could the items be slightly larger? They are not so easy to see.

**Comment by MichaelEischer** [comment]
Simply labeling the buttons with "Add folder" should solve the problem?

**Comment by Freudentaumel** [comment]
. . . maybe like this: **"Add folder"**
