### ISSUE TITLE
Feature Request: Make Subscribe button in URL/location bar optional.

### ISSUE THREAD

**Issue by akwala** [ancestorak/brief#291]
Thanks for porting to WE.

Use case: Not all subscriptions are to be added to Brief. The Subscribe button that comes with the browser (or a variation of it from an addon) offers choice of services/applications (including Brief) to which a subscription is to be added. The Subscribe button for Brief in the location bar is therefore redundant and wastes space.

Show the Subscribe button in the location bar based on a binary option in the addon's preferences.

**Comment by tanriol** [comment]
There will be no need to have a Brief option since Firefox 58 (in Beta now) as the UI to show/hide buttons from location bar will be built-in. Do you really need such an option for the transition period?

**Comment by akwala** [comment]
@tanriol I didn't know. If that's going to be built-in then there's no need to provide the option in Brief. Thanks.
