### ISSUE TITLE
Can't export feeds into OPML file

### ISSUE THREAD

**Issue by ezrider1** [ancestorak/brief#292]
Version 2.5.1 with FF57: I can't export feeds into an OPML file. When I try, no dialog box opens, nothing happens. Error message in the console:

`incorrect database  opml.js:71`

**Comment by tanriol** [comment]
Thank you for this error! Looks like one more problem with tree structure and hidden folders... I'll look into it.

**Comment by ezrider1** [comment]
To be more precise: I can export feeds **once** to an OPML file, but afterwards the export does not work any more. Maybe this helps.

**Comment by tanriol** [comment]
@ezrider1 Do you mean "once per browser restart" or "it worked the first time, and now it does not"?

**Comment by ezrider1** [comment]
I mean the latter; even if I restart the browser (and PC) the export does not work. I tried with a completely new Firefox profile to avoid conflicts with unusual settings or other add-ons, but the problem was the same. The export was possible once after installing Brief and then never again.

**Comment by tanriol** [comment]
With a new Firefox profile with some imported list of feeds or with none?

**Comment by ezrider1** [comment]
You asked the right question. I tested the following:
1. new Firefox profile
2. install Brief
3. subscribe to feeds using only Brief => multiple exports possible.
4. import OPML file generated with Thunderbird before into Brief. => export works once afterwards, but never again. (Problem described initially)

Apparently there is a problem with my OPML file from Thunderbird. I noticed earlier that Feedbro caused trouble as well: the message pane did not display any message content. I suspect this was due also to an  OPML file imported from Thunderbird.

**Comment by tanriol** [comment]
Wow! Would be very useful if you could share with me the file (possibly by e-mail) so that I could investigate and fix the bugs.

**Comment by ezrider1** [comment]
Hi, is this the address to reply to by e-mail when sending my OPML file?

**Comment by tanriol** [comment]
Please use `dennis.lissov@gmail.com`
