### ISSUE TITLE
pubDate is optional

### ISSUE THREAD

**Issue by jethrogb** [ancestorak/brief#294]
Some feeds, such as http://www.giantitp.com/comics/oots.rss, don't include a pubDate. This is indeed optional, according to the [specification](http://www.rssboard.org/rss-specification#ltpubdategtSubelementOfLtitemgt). However, Brief erroneously assigns the current time to items without a pubDate on every refresh, even when nothing changed. Edit: <s>Instead, Brief should remember the first time it saw such an item.</s>

**Comment by tanriol** [comment]
Brief remembers both the first time the item was seen and the last fetch time. The best option, in my opinion, would be to compare content and mark an item updated only if there are any changes. However, remembering only the first date and ignoring possible updates is rather suboptimal, isn't it?

**Comment by jethrogb** [comment]
Ah, I see. I'd say that if you don't put a date in your feed you're implicitly signaling you're not going to do updates. But a deep comparison would work too (it's just more work).

**Comment by tanriol** [comment]
Closing this as there's a more specific issue for update detection (#302) and a manual toggle to ignore updates in a specific feed.
