### ISSUE TITLE
Hiding the subscribe button

### ISSUE THREAD

**Issue by ghost** [ancestorak/brief#298]
I already have the native firefox subscribe button around, and brief's own button appearing and disappearing on the url bar is kinda distracting, as I can't even move it into the page actions menu. Is there some way to get rid of it?

**Comment by tanriol** [comment]
> ...as I can't even move it into the page actions menu.

Do you mean that you're on 57 that does not allow it yet or that there's some other problem with putting it there?

**Comment by JellyVeggie** [comment]
...ah, yes, I'm on 57. Sorry for bothering you

**Comment by bdcomp** [comment]
Right clicking the subscribe button (end of address bar), the option "Remove from Toolbar" is inactive. The Customize mode not relevant to the address bar items, as well.
So, please add an option to remove it.

Brief 2.5.2
Firefox 57
Kubuntu 17.10 64bit

**Comment by tanriol** [comment]
@bdcomp, the built-in option will become available in Firefox 58.

**Comment by tanriol** [comment]
Closing this bug as the feature asked for is available in the current Firefox version.
