### ISSUE TITLE
Read items from YouTube RSS feed show up as 'updated' every feed refresh

### ISSUE THREAD

**Issue by VillageCatDad** [ancestorak/brief#300]
One thing for which I use Brief is to track updates to various YouTube channels that I follow.  Even though I've marked items as 'read', the next time Brief does a refresh of the feeds, all the previously read items show back up as 'updated', with the same timestamp (e.g., 'one hour ago') on them.  I exported the RSS feeds from YouTube using the instructions provided by YouTube in the Subscription Manager page.  This was not an issue when I was using Bamboo as my RSS reader, so it mush be something in Brief's code.

**Comment by tanriol** [comment]
Will be tracking the problem in #302.
