### ISSUE TITLE
Transparent background of logo

### ISSUE THREAD

**Issue by bdcomp** [ancestorak/brief#305]
You should update the extension's icon (from the Mozilla developer hub and/or bundled with the extension) to include a transparent background.
Currently icon with white background, used inside the Firefox add-on manager and on Firefox add-ons pages (detail page, search results, etc.), looks bad.

Brief 2.5.2
Firefox 57
Kubuntu 17.10 64bit

**Comment by tanriol** [comment]
Could you please help me investigate this problem? I've just checked all the Brief icons I found and my viewer showed them with transparent background. I don't know the source of this problem. Are the files incorrect for some reason?

**Comment by bdcomp** [comment]
So, it's probably here:
https://addons.mozilla.org/developers/addon/brief/edit
Images -> Add-on icon: do you have 2 icons?

**Comment by tanriol** [comment]
Updated and, at least on AMO, seems to be ok.
