### ISSUE TITLE
Trouble loading Brief

### ISSUE THREAD

**Issue by mjr66** [ancestorak/brief#309]
I'm finding that the Brief page is somewhat temperamental about loading. Sometimes I click on the icon to load it, and everything is fine, but most times, I am just presented with a blank page, like so -

![image1](https://user-images.githubusercontent.com/15090612/33215480-d8e16c38-d127-11e7-8bf1-d6e5fa0dd6d3.png)

Before turning blank, there's an error message that flashes up on the screen for a brief instant ("Hmm. That address doesn't look right."). Once the screen is blank, none of the buttons/links on the page respond to clicks (although they change colour etc if I mouse over them).

If I refresh the page a few times, or click on the icon to open a second (or third, etc) tab, then eventually the feeds populate and I have a working Brief page -

![image2](https://user-images.githubusercontent.com/15090612/33215769-dc37cfac-d128-11e7-8d20-965435aba61e.png)

Any ideas? I'd love to get Brief working again :)

This in a completely fresh install of Firefox 57 (64-bit), with no other addons installed.

**Comment by tanriol** [comment]
When a newly opened tab finally loads, have the other Brief tabs opened before loaded too?

If you open the Brief tab, open the developer tools with F12 and switch to the "console" tab, are there any messages from Brief?

**Comment by mjr66** [comment]
> When a newly opened tab finally loads, have the other Brief tabs opened before loaded too?

No, they just remain blank and unresponsive.

> If you open the Brief tab, open the developer tools with F12 and switch to the "console" tab, are there any messages from Brief?

![image3](https://user-images.githubusercontent.com/15090612/33225664-dc016372-d173-11e7-932f-866a2aaf778e.png)

Does that help?

**Comment by tanriol** [comment]
Looks like a race condition on init... ok, I'll try to fix it in 2.5.4.

**Comment by Ulysses1337** [comment]
I updated FF to 57 today and it auto updated Brief to 2.5.4 right away. I get the blank unresponsive UI every single time, but with different console output:

`Brief: opening database in persistent storage` `database.js:43:9`
`InvalidStateError` `database.js:48:21`

**Comment by mjr66** [comment]
At first glance, bug seems to have been fixed for me. Thanks very much :)

**Comment by tanriol** [comment]
@Ulysses1337 The traditional question: do you have nonstandard and/or very strict privacy options? For data storage Brief needs the permission to open its IndexedDB database. Your error looks like it's failing to do that, possibly denied access.

**Comment by Ulysses1337** [comment]
I went through all my modified items in about:config. Nothing caught my eye.

However I do `Never remember history`. I seem to be a victim of https://bugzilla.mozilla.org/show_bug.cgi?id=781982. This makes me a sad panda.

**Comment by tanriol** [comment]
More like [1313401](https://bugzilla.mozilla.org/show_bug.cgi?id=1313401), but yes, that seems to be the problem.
