### ISSUE TITLE
Parsing some feeds

### ISSUE THREAD

**Issue by lollyP** [ancestorak/brief#314]
Brief seems to fail to parse some feeds. I'm not an expert so can't add an analysis, but an example is the ExifTool feed here http://owl.phy.queensu.ca/~phil/exiftool/rss.xml, which does seem to have a problem identified by https://validator.w3.org/feed/check, but equally is parsed by, eg, Feedbro.

I'm using the latest Brief version 2.5.4 on FF57.

Thanks!

**Comment by tanriol** [comment]
Fixed in 2.5.5 (f788035d71598abd2afe4a8d3f374feda5306071).
