### ISSUE TITLE
Control-Shift-D to save bookmarks makes all Brief entries bookmarked in Brief

### ISSUE THREAD

**Issue by sleek22** [ancestorak/brief#325]
On Firefox 57.0 and Brief 2.5.5, if I press Control-Shift-D to save a group of bookmarks, all items in Brief become bookmarked, i.e., the gold star shows on all items and in the Brief Bookmarks count. Deleting the folder makes the bookmarks go away.

The bookmarks in Brief are not really saved anywhere as far as I can tell because I can't find them in my bookmarks. If I toggle the gold star off and back on again on on item, that one item shows up in the Other Bookmarks folder.

I disabled all add-ons that have anything to do with bookmarking but the problem still happens.

**Comment by tanriol** [comment]
> Control-Shift-D to save a group of bookmarks

Where does this shortcut come from? I don't see it anywhere.

**Comment by sleek22** [comment]
It's the standard Firefox command to bookmark all tabs. You can see it here as the first entry under the section Bookmarks:

[https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly](url)

**Comment by jibe-b** [comment]
I still need where it comes from but tons of Brief items get starred without actually starring them. (FF57)

**Comment by tanriol** [comment]
Ok, this looks like an alternate version of #340 and will be fixed in 2.5.6. Let's have that issue as the tracking one and close this one.
