### ISSUE TITLE
[Fx18] Apply custom style without reloading the document

### ISSUE THREAD

**Issue by ancestorak** [ancestorak/brief#36]
[nsIDOMWindowUtils.loadStyleSheet()](http://mxr.mozilla.org/mozilla-central/source/dom/interfaces/base/nsIDOMWindowUtils.idl#1327), introduced in Firefox 18, lets us get rid of the entire resource alias business and makes it possible to apply the stylesheet without reloading the document.

**Comment by tanriol** [comment]
This API will not be available to WebExtensions.
