### ISSUE TITLE
Cannot find chrome://brief/content/brief.xhtml

### ISSUE THREAD

**Issue by jomoncon** [ancestorak/brief#360]
All of a sudden I'm getting the following error message when trying to subscribe to a page:

Firefox can’t find the file at chrome://brief/content/brief.xhtml?subscribe=http://www.punkdomestics.com/taxonomy/term/1/all/feed.

I even uninstalled & reinstalled Brief. Lost all my pages doing this. I'm running Firefoix 60.0.1

**Comment by tanriol** [comment]
The subscribe page workflow is not working right now. Will be partially fixed in the next update.

**Comment by jomoncon** [comment]
I refreshed firefox. When I reloaded the Brief app, it's now working.
