### ISSUE TITLE
Enter key shortcut is activating unintentionally

### ISSUE THREAD

**Issue by Keith94** [ancestorak/brief#48]
If you have the Brief tab focused and you carry out a search in Firefox's search bar or navigate to a website from the location bar, it will also open the current feed item (if there's one visible) in a new tab at the same time as doing the other things (when you press the enter key). So I'd prefer if Brief didn't do that while using the search/location bars if possible.

**Comment by tanriol** [comment]
I've moved the listeners into the Brief tab as a part of migrating to XUL-less Brief. Fixed.

**Comment by Keith94** [comment]
Cool. :)
