### ISSUE TITLE
New toolbar icon is too big on Mac

### ISSUE THREAD

**Issue by svoop** [ancestorak/brief#96]
The update to 1.7.3 brings a new toolbar icon which is too big - at least on my Retina Mac with the latest version of Firefox.

Without 1.7.3:
![screen shot 2014-10-08 at 09 36 19](https://cloud.githubusercontent.com/assets/7255/4555491/4d9e5aa8-4ebe-11e4-8c23-f5bfccd3dec0.png)

With 1.7.3:
![screen shot 2014-10-08 at 09 36 48](https://cloud.githubusercontent.com/assets/7255/4555494/55bb8fc6-4ebe-11e4-8bbe-3df7f9f5aaef.png)

With 1.7.2:
![screen shot 2014-10-08 at 09 42 34](https://cloud.githubusercontent.com/assets/7255/4555539/cdf8a6fe-4ebe-11e4-8d24-02e91b529f04.png)

**Comment by kodabb** [comment]
any update on this?
